### ISSUE TITLE
Interdomain tests are unstable

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/integration-interdomain-k8s#55]
## Description

Interdomain tests are not working see at https://github.com/networkservicemesh/integration-interdomain-k8s/pull/54

Potential cause: https://github.com/networkservicemesh/sdk/pull/1072

We need to investigate and solve all issues that make CI red.

**Comment by edwarnicke** [comment]
I think this is fixed: https://github.com/networkservicemesh/integration-k8s-kind/pull/367 :)

**Comment by denis-tingaikin** [comment]
It seems like the problem is not related to `begin`.

**Comment by denis-tingaikin** [comment]
Closing due Is not reproducing.
